name: besmart_traveler
description: Mobile application to find local trips in Kyrgyzstan
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  http: ^0.13.5
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  sqflite: ^2.2.6
  path: ^1.8.2
  hive: ^2.2.3
  path_provider: ^2.0.14
  datetime_picker_formfield: ^2.0.0
  url_launcher: ^6.0.3
  file_picker: ^5.2.7
  scroll_page_view: ^1.0.2
  intl: ^0.17.0
  flutter_icons_null_safety: ^1.1.0
  flutter_svg: ^2.0.5
  quickalert: ^1.0.1
  photo_view: ^0.14.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#7DBBC3"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/homepage/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
